management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: read_only
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
  health:
    ldap:
      enabled: false

info:
  app:
    name: @project.artifactId@
